// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvcIfBI0j19GQCtNcMT0ddEOcBIQZtxLg',
    appId: '1:467836780703:web:214a64c86be8debf0d62aa',
    messagingSenderId: '467836780703',
    projectId: 'weatherapp-e2a08',
    authDomain: 'weatherapp-e2a08.firebaseapp.com',
    storageBucket: 'weatherapp-e2a08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSHVRMPfpDVejDqAHY0s1aHBMmFVUMKk',
    appId: '1:467836780703:android:bce2e7cb38582c400d62aa',
    messagingSenderId: '467836780703',
    projectId: 'weatherapp-e2a08',
    storageBucket: 'weatherapp-e2a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVbmqtTNPSXeQWgkJd6bgF8HtsYzO3sI',
    appId: '1:467836780703:ios:39f4cc2a7d7694a60d62aa',
    messagingSenderId: '467836780703',
    projectId: 'weatherapp-e2a08',
    storageBucket: 'weatherapp-e2a08.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfVbmqtTNPSXeQWgkJd6bgF8HtsYzO3sI',
    appId: '1:467836780703:ios:39f4cc2a7d7694a60d62aa',
    messagingSenderId: '467836780703',
    projectId: 'weatherapp-e2a08',
    storageBucket: 'weatherapp-e2a08.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvcIfBI0j19GQCtNcMT0ddEOcBIQZtxLg',
    appId: '1:467836780703:web:d3b9cdcfe947b21b0d62aa',
    messagingSenderId: '467836780703',
    projectId: 'weatherapp-e2a08',
    authDomain: 'weatherapp-e2a08.firebaseapp.com',
    storageBucket: 'weatherapp-e2a08.firebasestorage.app',
  );
}
